### ISSUE TITLE
Nested objects don't work in useForm

### ISSUE THREAD

**Issue by illogikal** [formidablejs/view#9] opened 2022-05-08 14:40 UTC
https://github.com/formidablejs/framework/issues/121

**Comment by illogikal** [comment] 2022-05-08 15:31
'/aaa/a.js' also does not work as a key in the form

**Comment by donaldp** [comment] 2022-05-08 15:34
Hey @illogikal thanks for reporting the issue.

I've pushed out a new version with the fix.
Please update to `@formidablejs/view:0.1.6` to install the fix:

```bash
yarn add @formidablejs/view
# or
npm i @formidablejs/view
```

**Comment by illogikal** [comment] 2022-05-08 15:35
Does this fix the slash object key bug also?

**Comment by donaldp** [comment] 2022-05-08 16:05
Ahh, it doesn't look like that was fixed. I did more debugging. The problem seems to be the full stop `.`. The issue is external. Probably a bug in one of the fastify plugins responsible for reading the http body.

For now, I'd suggest you remove the `.` from the key. Or maybe replace it with a different char.

**Comment by illogikal** [comment] 2022-05-08 16:16
Alright thanks. The latest verstion of the useForm seems to now refresh the page? I'm not using it with a form, i'm using it as a standalone function...

**Comment by donaldp** [comment] 2022-05-08 16:18
Do you mind sharing your code? And the function calling the useForm persist request function?

**Comment by illogikal** [comment] 2022-05-08 16:34
I messaged you on discord

**Comment by donaldp** [comment] 2023-05-06 08:35
Closing this for now.

Issue seems to be period related: `.`. Removing the period seems to fix the issue.
```imba
def mount
    useForm({
        '/aaa/a': [
            {
                name: 'Don'
            }
            {
                name: 'Luna'
            }
        ]
    }).on('test')
```

**Closed by donaldp** 2023-05-06 08:35 UTC
